# # ARCHIVE = lib.a
# NAME = so_long
# CC = cc
# FLAGS = -Wall -Wextra -Werror

# LIBA_PRINTF = libs/ft_printf/libftprintf.a
# LIBA_LIBFT = libs/libft/libft.a
# LIBA_GNL = libs/get_next_line/gnl.a
# LIBA_UTILS = utils/utils.a
# LIBS = -lmlx -framework OpenGL -framework Appkit

# OBJ_FILES = $(SRC_FILES:.c=.o)

# all: ${NAME}

# ${LIBA_PRINTF}:
# 	make -C libs/ft_printf/

# ${LIBA_LIBFT}:
# 	make -C libs/libft/

# ${LIBA_GNL}:
# 	make -C libs/get_next_line/

# ${LIBA_UTILS}:
# 	make -C utils/

# ${NAME}: ${LIBA_PRINTF} ${LIBA_LIBFT} ${LIBA_GNL} ${LIBA_UTILS}
# 	${CC} ${FLAGS} src/main.c -o ${NAME} ${LIBS} ${LIBA_UTILS} ${LIBA_PRINTF} ${LIBA_LIBFT} ${LIBA_GNL}

# clean:
# 	rm -f ${OBJ_FILES}
# 	make clean -C libs/libft/
# 	make clean -C libs/ft_printf/
# 	make clean -C libs/get_next_line/
# 	make clean -C utils/

# fclean: clean
# 	rm -f ${NAME}
# 	make fclean -C libs/libft/
# 	make fclean -C libs/ft_printf/
# 	make fclean -C libs/get_next_line/
# 	make fclean -C utils/

# re: fclean all